server:
  compression:
    enabled: true
spring:
  datasource:
    name: mytrack
    url: jdbc:mysql://119.3.156.32:3306/mytrack?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: guit1951300134
    druid:
      initial-size: 5
      max-active: 10
      max-wait: 100
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      filters: stat,wall
  mvc:
    format:
      date: iso
      time: iso
      date-time: iso
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8

jakarta:
  validation:
    constraints:
      Min:
        message: "最小值为${min}"